#!/usr/bin/env bash

# ========================================
# IVWA - READY TO RUN
# ========================================
# 
# Selamat! Aplikasi IVWA sudah siap digunakan!
# Berikut adalah instruksi cara menjalankannya.
#
# ========================================

echo ""
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║                                                                ║"
echo "║  ✅ IVWA - INTENTIONAL VULNERABLE WEB APPLICATION             ║"
echo "║                                                                ║"
echo "║  Aplikasi pembelajaran cybersecurity sudah LENGKAP dan SIAP!   ║"
echo "║                                                                ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

echo "📦 PROJECT STRUCTURE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Core Application Files:"
echo "  ✓ index.php              - Welcome page"
echo "  ✓ login.php              - SQL Injection vulnerability"
echo "  ✓ dashboard.php          - Stored XSS vulnerability"  
echo "  ✓ search.php             - Reflected XSS vulnerability"
echo "  ✓ logout.php             - Logout functionality"
echo ""
echo "Configuration & Database:"
echo "  ✓ config/db.php          - Database configuration"
echo "  ✓ database/init.sql      - Database schema & data"
echo ""
echo "Frontend & Assets:"
echo "  ✓ assets/style.css       - Professional styling"
echo "  ✓ assets/secure-examples.php - Secure implementations"
echo ""
echo "Documentation:"
echo "  ✓ README.md              - Lengkap documentation (Bahasa Indonesia)"
echo "  ✓ QUICKSTART.md          - 5-minute quick start"
echo "  ✓ INSTALLATION.md        - Step-by-step setup"
echo "  ✓ PAYLOADS.md            - Payload examples"
echo "  ✓ PROJECT_STRUCTURE.md   - Project overview"
echo "  ✓ COMPLETION_CHECKLIST.md - Setup checklist"
echo ""

echo "🚀 QUICK START (3 STEPS)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Step 1: Import Database"
echo "  $ mysql -u root < database/init.sql"
echo ""
echo "Step 2: Start Web Server (pilih salah satu):"
echo "  Opsi A - XAMPP/LAMPP:"
echo "    $ /opt/lampp/lampp start"
echo ""
echo "  Opsi B - Apache & MySQL:"
echo "    $ sudo systemctl start apache2"
echo "    $ sudo systemctl start mysql"
echo ""
echo "Step 3: Open Browser"
echo "  http://localhost/myOwn-ivwa"
echo ""
echo "Login dengan:"
echo "  Username: admin"
echo "  Password: password123"
echo ""

echo "🧪 TEST VULNERABILITIES (QUICK TESTS)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Test 1: SQL Injection (di Login)"
echo "  Username: admin' OR '1'='1"
echo "  Password: anything"
echo "  → Tekan Login → Anda akan berhasil login!"
echo ""
echo "Test 2: Stored XSS (di Dashboard)"
echo "  Comment: <img src=x onerror=\"alert('XSS')\">"
echo "  → Tekan Post → Refresh halaman → Alert akan muncul!"
echo ""
echo "Test 3: Reflected XSS (di Search)"
echo "  Buka URL ini (copy-paste ke address bar):"
echo "  http://localhost/myOwn-ivwa/search.php?q=%3Cimg%20src=x%20onerror=%22alert('XSS')%22%3E"
echo "  → Alert akan muncul!"
echo ""

echo "📚 RECOMMENDED READING"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. QUICKSTART.md          (5 menit)   ← START HERE"
echo "2. PROJECT_STRUCTURE.md   (10 menit)"
echo "3. README.md              (30 menit)  ← Dokumentasi lengkap"
echo "4. PAYLOADS.md            (20 menit)  ← Learn testing"
echo "5. INSTALLATION.md        (15 menit)  ← Setup detail"
echo ""

echo "🔑 DEMO ACCOUNTS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Username: admin   | Password: password123"
echo "Username: user1   | Password: password123"
echo "Username: user2   | Password: password123"
echo "Username: hacker  | Password: password123"
echo ""

echo "🎯 VULNERABILITIES"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. SQL Injection (SQLi)           - File: login.php"
echo "   Severity: 🔴 CRITICAL"
echo "   Impact: Bypass authentication, steal data"
echo "   Fix: Use prepared statements"
echo ""
echo "2. Stored XSS (Persistent XSS)    - File: dashboard.php"
echo "   Severity: 🔴 CRITICAL"
echo "   Impact: Execute JavaScript for all users"
echo "   Fix: Escape HTML output dengan htmlspecialchars()"
echo ""
echo "3. Reflected XSS                  - File: search.php"
echo "   Severity: 🟠 HIGH"
echo "   Impact: Execute JavaScript for user"
echo "   Fix: Escape URL parameters saat display"
echo ""

echo "⚠️  IMPORTANT REMINDERS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ DO:"
echo "   • Use HANYA di localhost/sandbox"
echo "   • Gunakan untuk pembelajaran"
echo "   • Read dokumentasi lengkap"
echo "   • Experiment dengan payloads"
echo "   • Practice ethical hacking"
echo ""
echo "❌ DONT:"
echo "   • Deploy ke production"
echo "   • Use untuk unauthorized testing"
echo "   • Test di sistem orang lain tanpa izin"
echo "   • Use untuk purposes illegal"
echo ""

echo "🛠️ TROUBLESHOOTING"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Problem: Connection refused"
echo "Solution: Pastikan MySQL running - mysql -u root"
echo ""
echo "Problem: Database doesn't exist"
echo "Solution: Import database - mysql -u root < database/init.sql"
echo ""
echo "Problem: Cannot access application"
echo "Solution: Check if Apache running - systemctl status apache2"
echo ""
echo "Problem: CSS not loading"
echo "Solution: Hard refresh - Ctrl+Shift+R"
echo ""
echo "Untuk lebih banyak help, lihat INSTALLATION.md"
echo ""

echo "📞 GETTING HELP"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Read dokumentasi file (.md files)"
echo "2. Check PAYLOADS.md untuk testing tips"
echo "3. Review INSTALLATION.md untuk setup"
echo "4. See PROJECT_STRUCTURE.md untuk overview"
echo ""

echo "🎓 LEARNING OBJECTIVES"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Setelah menggunakan IVWA, Anda akan memahami:"
echo ""
echo "✓ Bagaimana SQL Injection terjadi dan dampaknya"
echo "✓ Perbedaan Stored XSS dan Reflected XSS"
echo "✓ Mengapa input validation dan output encoding penting"
echo "✓ Best practices dalam secure web development"
echo "✓ Cara melakukan security testing"
echo "✓ Ethical hacking principles"
echo ""

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║                                                                ║"
echo "║               🚀 READY TO START LEARNING! 🚀                  ║"
echo "║                                                                ║"
echo "║  Next step: Read QUICKSTART.md untuk setup 5-menit            ║"
echo "║                                                                ║"
echo "║               Happy Learning! 🎓 Use Responsibly!             ║"
echo "║                                                                ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "Version: 1.0"
echo "Created for educational purposes only"
echo "Use ethically and responsibly!"
echo ""
